CREATE TABLE celdas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    objeto VARCHAR(255) NOT NULL,
    estado TINYINT(1) NOT NULL DEFAULT 0,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);